name: music_firebase
description: "A new Flutter project."
# cuenta ----- jornegrepluss@gmail.com
# proyecto --- music-firebase
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  get: ^4.6.6
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  syncfusion_flutter_gauges: ^23.1.42
  on_audio_query: ^2.9.0
  permission_handler: ^11.0.1
  just_audio: ^0.9.35
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
 
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
 