// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKfEapWieqC0V1T8s2SMv9vh_Duf-Qf44',
    appId: '1:832244124790:web:794899a19b55c57fca2357',
    messagingSenderId: '832244124790',
    projectId: 'music-firebase-3671d',
    authDomain: 'music-firebase-3671d.firebaseapp.com',
    storageBucket: 'music-firebase-3671d.appspot.com',
    measurementId: 'G-DFL15Q37VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-W6KlSG1ZQtCWUU5r9xVxa28_gJgfxw',
    appId: '1:832244124790:android:e4d887d1042748a7ca2357',
    messagingSenderId: '832244124790',
    projectId: 'music-firebase-3671d',
    storageBucket: 'music-firebase-3671d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwSej_K4bg0gi2Z8_vk6REqUgsRRaXEDc',
    appId: '1:832244124790:ios:198ccc3a555b4269ca2357',
    messagingSenderId: '832244124790',
    projectId: 'music-firebase-3671d',
    storageBucket: 'music-firebase-3671d.appspot.com',
    iosBundleId: 'com.johonbar.musicFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwSej_K4bg0gi2Z8_vk6REqUgsRRaXEDc',
    appId: '1:832244124790:ios:700aadb389b71c40ca2357',
    messagingSenderId: '832244124790',
    projectId: 'music-firebase-3671d',
    storageBucket: 'music-firebase-3671d.appspot.com',
    iosBundleId: 'com.johonbar.musicFirebase.RunnerTests',
  );
}
